### ISSUE TITLE
Add ability to auto-recover from a failing collector

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-dotnet-tracker#14]
See https://github.com/snowplow/snowplow-python-tracker/issues/151

**Comment by digitaltouch** [comment]
The functionality is not immediately sticking out to me in the Python tracker, but as I looked further into the way the dotnet-tracker is built, it I think the functionality may already be accessible through the existing Emitter class:

https://github.com/snowplow/snowplow-dotnet-tracker/blob/b7942a9acc98cd75ea9127fdfb6695e955135e87/Snowplow.Tracker/Emitters/Emitter.cs#L146

Since the event that is returned to onFailure contains the original payload that was added to the buffer, by simply reinserting the event into the buffer the same objective can be achieved. 

    foreach (Dictionary<string,string> eventPayload in unsentEvents) {
         e.Input(eventPayload)
    };

    //manually flush
      t.Flush(false);

Please note that if the event fails again, it will be duplicated in the onFailure list created earlier.  Maybe some sort of de-duping in the list before flushing? We could also encounter an infinite loop if the HttpResonse is never "OK".

I am happy to work on implementing this functionality, however, I think it needs some additional planning.

**Comment by alexanderdean** [comment]
It could be helpful to understand how the mobile trackers achieve this - @jbeemster?

**Comment by jbeemster** [comment]
The mobile trackers have a persistent SQLite database storing all of the events.  So they are simply never removed from the database until they are successfully sent.  

Perhaps we need a better queue than the buffer to store and remove events from and to only remove them from said queue on successfully sending them?  It seems easier than constantly re-adding failed events to the buffer.

**Comment by alexanderdean** [comment]
Thanks Josh - @digitaltouch / @fblundun, what would be a sensible equivalent of SQLite for a .NET tracker?

**Comment by digitaltouch** [comment]
MSMQ will probably be the easiest to extend.  There is already a MSMQ emitter implemented... Working to better understand the "Offline" logic built into the tracker already.  May be easiest to keep everything implemented as is, just add any events without an "OK" response to the Queue, not just unavailable events:

https://github.com/snowplow/snowplow-dotnet-tracker/blob/master/Snowplow.Tracker/Emitters/Emitter.cs#L239

Thoughts @fblundun?

**Comment by fblundun** [comment]
I've added some documentation on the simplest way to achieve this with the Python Tracker [here](https://github.com/snowplow/snowplow/wiki/Python-Tracker#58-automatically-retry-sending-failed-events). It works in a similar manner to @digitaltouch's original suggestion, feeding failed events back into the emitter's `input` function.

You are right that this approach would be problematic in the this Tracker if offline mode is enabled - every failed event would both be fed back in to the original emitter and sent to the "backup emitter".

The way the backup emitter currently works, if sending an event throws a WebException the event is stored in an MSMQ queue. Whenever there is a network availability change event, we attempt to resend those failed events.

Sending all events without an OK response to the queue, rather than just those which throw a WebException, sounds good to me!

**Comment by alexanderdean** [comment]
Thanks @fblundun . Sending all events without an OK response to the queue sounds like the way to go!

**Comment by digitaltouch** [comment]
Making progress - 

https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/master/Snowplow.Tracker/Emitters/Emitter.cs#L215-L242

All that was added was offlineHandle(payload) and offlineHandle(data)

I received a strange error when the MSMQ got 15 records or more:

"system.invalidoperationexception collection was modified enumeration may not execute" and it was pointing to: https://github.com/digitaltouch/snowplow-dotnet-tracker/blob/master/Snowplow.Tracker/Emitters/Emitter.cs#L170

Did you see anything like this when writing the tracker?

Just ran around 1,000,000 records through with around 1,000 unsuccessful being added to the MSMQ and successfully flushing.

**Comment by fblundun** [comment]
That's interesting... The fact that this happens intermittently suggests a concurrency bug. It could caused by the absence of a lock on the `tasks` list - perhaps [these two lines](https://github.com/snowplow/snowplow-dotnet-tracker/blob/958042e0594a35662abf30f89097ed3049f03cbe/Snowplow.Tracker/Emitters/AsyncEmitter.cs#L63-L64) are being executed concurrently?

My hypothesis is that the exception occurs when one thread is inserting into the tasks list with while another thread is calling `.toList()` on it.

**Comment by fblundun** [comment]
Does it still happen if you do something like this?

```csharp
    private readonly object Locker = new object();
        
    protected override void Flush(bool sync, bool forced)
    {
        lock(Locker)
        {
            Task flushingTask = Task.Factory.StartNew(() =>
            {
                if (forced || this.buffer.Count >= this.bufferSize)
                {
                    SendRequests();
                }
            });
            tasks.Add(flushingTask);
            tasks = tasks.Where(t => !t.IsCompleted).ToList();

            if (sync)
            {
                Log.Logger.Info("Starting synchronous flush");
                Task.WaitAll(tasks.ToArray(), 10000);
            }
            else
            {
                Thread.Yield();
            }
        }
    }
```

**Comment by fblundun** [comment]
To answer your original question, I don't remember ever seeing this exception when I was originally developing the Tracker. Perhaps I wasn't using high enough event volumes for it to become apparent.

**Comment by digitaltouch** [comment]
Great catch... I was scratching my head on this most of the day yesterday.  

It has run successfully for an hour so far with the lock on the `tasks` list.  I will monitor of the next couple of days and then issue the Pull Request if everything appears to be working.

**Comment by fblundun** [comment]
Glad to hear it! Let us know if anything else goes wrong...

**Comment by alexanderdean** [comment]
Not sure why Ed closed this, it will close on merge to master
