### ISSUE TITLE
Fix concurrency bug which causes some events to be silently dropped

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-dotnet-tracker#17]
As reported [here](https://groups.google.com/forum/#!topic/snowplow-user/ylJ1bqVmGNY).

**Comment by digitaltouch** [comment]
@fblundun - I just realized that when originally reporting this on google groups, I had already addressed this in issue #14 with PR #15. 

We have been using our fork of the tracker in production since the PR was made. The ability to recover from a failing collector has proven to work very well when combined is MSMQ.   This has eliminated events that go missing due to network issues or a failing collector. 

As far as the concurrency bug, I believe the lock should have stopped events from being dropped.  In the thread mentioned above I suggested implementing an Asynchronous method.  Prior to implementing this, we began testing with the Clojure collector, and were unable to recreate the "missing" events.  We are now running the Clojure collector and the non `AsyncEmitter` with HTTP.POST  in production with no data loss.

A few notes on the original use case:
-We run the collector for batch loading of large delimited files.  The machine will open thousands of concurrent connections if allowed.
-When CloudFront reaches its request limit, it sends a request denied - prompting the event to be written to MSMQ.  Event is re-sent when the collector responds with a success message.
-We were able to re create the missing events with Asynchronous and Synchronous emitter. It seems to be completely random.  Certain batches would be missing more than others, some wouldn't be missing any events.

Do you have any other recommendation / ideas?  It is entirely possible that CloudFront is losing data in log rotation, but hard to imaging that it would be as high as 5%. Willing to do whatever it takes to get this solved.

**Comment by fblundun** [comment]
Hi @digitaltouch ,

It's interesting that you're only seeing problems with the CloudFront Collector, not the Clojure Collector. It sounds like you have only been sending requests to the Clojure Collector by POST so far. It would be interesting to try to duplicate the issue sending to the Clojure Collector by GET. If the events are dropped, that's evidence that the problem is with the tracker's implementation of sending requests by GET; otherwise it's evidence that the problem is with CloudFront logging.

I agree that CloudFront dropping 5% of events would be surprising, but it is conceivable. In general we recommend using the Clojure Collector over the CloudFront Collector, since it's specifically written for the purpose of logging Snowplow events.

**Comment by digitaltouch** [comment]
We did test with GET but found immediate efficiencies with the batched POST with the Clojure collector so we moved on. 

Its a rather time consuming test to perform, so this may take some time - but we will get back to you with a GET test on the Clojure collector.

**Comment by fblundun** [comment]
@digitaltouch thanks for doing this - we will be very interested to hear the results...

**Comment by alexanderdean** [comment]
Not sure why Ed closed this, it will close on merge to master
