### ISSUE TITLE
Fix "duplicate _id" bug where IDs become non-unique

### ISSUE THREAD

**Issue by ninjabear** [snowplow/snowplow-dotnet-tracker#69]
This is caused by a change in the underlying library - we need to generate our own IDs to ensure they are unique

**Comment by solcarty** [comment]
I believe the problem is that you **are** generating your own auto numbers.
If you remove the newId line you will get a built-in id which is also an auto number starting at 1 and should fix any concurrency issues.

```
            BsonMapper.Global.RegisterAutoId<string>
            (
                isEmpty: (value) => value == null || value.Trim() == "",
                newId: (db, col) => ""+db.Count(col, null)
            );
```
Alternately you could use something like Ticks

`newId: (collection) => DateTime.UtcNow.Ticks`

[LiteDB AutoID](https://github.com/mbdavid/LiteDB/wiki/LiteDB-v1#autoid)

**Comment by ninjabear** [comment]
You're right - that is the piece of code causing the problem. By generating our own ids, in this context I mean not trusting the value of `db.Count`. 

I know using ticks is in the docs but the resolution of ticks is too low to generate unique ids reliably.
